name: running test, build image push image to docker hub, and deploy to ec2

on:
  push:
    branches: [main]

jobs:
  running-test:
    name: Running Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - name: Run Test
        run: go test -v ./... -cover

  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    needs: running-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -name: 
        run: docker build -t aditnugroho/go-wishlist-aws:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Image
        run: docker push aditnugroho/go-wishlist-aws:latest

  deploy-to-ec2:
    name: Deploy To EC2
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/go-wishlist-aws
            docker pull aditnugroho/go-wishlist-aws
            docker run -d --name go-wishlist-aws -p 80:1323 aditnugroho/go-wishlist-aws
